### PR TITLE
Run test suite with GitHub Actions

### PR DESCRIPTION
**Pull request by bittner**
With GitHub Actions we can run the entire test suite against all supported  target operating systems and Python versions.

This will obsolete the use of Travis CI (for Linux and macOS builds) and AppVeyor (for Windows builds).

Fixes: #108

### CODE REVIEW

**Comment by cool-RR** [comment]
I guess that this PR isn't ready for my review yet, since the CI is failing? What do you think about opening these kind of PRs as draft until they're ready?

**Comment by cool-RR** [comment]
I'm unsubscribing so I won't get any more notifications every time you push a commit. Tag me when you're ready for a review.

**Comment by bittner** [comment]
This was a tricky one to solve again. On Linux there is a dependency that needs to be installed on the CI services, which seems to have changed (or at least on Ubuntu 18.4 a new package solves the dependency).

For details on that see https://github.com/wxWidgets/Phoenix/issues/1028.

@cool-RR Please review and merge now. Thank you!

**Review by cool-RR — APPROVED** [review]

**Comment by bittner** [comment]
As a side note, this finally supersedes PR #127 with a now fully working solution.

**Pull request merged**
