### PR TITLE
GitHub Action: Python 3.9 release candidate 2

### PR DESCRIPTION
**Pull request by cclauss**
https://www.python.org/download/pre-releases/

### CODE REVIEW

**Comment by bittner** [comment]
Your current changes don't run any tests. You'd have to extend the Tox configuration ([envlist](https://github.com/PythonTurtle/PythonTurtle/blob/master/tox.ini#L16) and [gh-actions](https://github.com/PythonTurtle/PythonTurtle/blob/master/tox.ini#L49)) accordingly.

Can you also describe why you think this is important to add to our setup? Why, e.g., would it not be fine to wait for a final, stable release of v3.9? Think in both the context of a desktop application and its development.

**Comment by cclauss** [comment]
### Why test Python 3.9 before it is released?
1. We could find bugs in Python 3.9... From the release notes:
> This release, 3.9.0rc2, is the last preview before the final release of Python 3.9.0 on 2020-10-05. In the mean time, we **strongly encourage** maintainers of third-party Python projects to prepare their projects for 3.9 compatibility during this phase. As always, report any issues to the Python bug tracker.
2. Many Python 3.9 breaking changes could effect our code, our build process, or our dependencies.
    * https://docs.python.org/3.9/whatsnew/3.9.html#porting-to-python-3-9
3. We could warn our dependencies that they have incompatibilities in code or processes.
4. In two weeks users will be asking if they can run on the current version of Python and we should prepare an answer.

**Comment by cool-RR** [comment]
Hi @cclauss , thanks for being our newest contributor. I'll let @bittner continue managing this pull request. I'm guessing your contribution is less about PythonTurtle and more about CI, which is fine. In case you were interested in helping the goals of PythonTurtle, the only issue that's important is #107. Right now all the code in this repo is unusable by the children who are the target audience of this project, and that issue aims to fix that.

**Comment by bittner** [comment]
The failing builds fail for wxPython. This looks like it's not building successfully with Python 3.9. It likely doesn't depend on us.

**Comment by cclauss** [comment]
When you say wxPython, do you mean:
* https://github.com/wxWidgets/wxPython-Classic --or--
* https://github.com/wxWidgets/Phoenix
If the latter then as I wrote above that builds successfully on Py39rc1.

**Comment by bittner** [comment]
It's whatever is installed with `pip install wxPython`. The problem is explained at the [top of the `tox.ini` file](https://github.com/PythonTurtle/PythonTurtle/blob/master/tox.ini#L1-L8).

Maybe if you use `https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04` with the [`pip install` command](https://github.com/PythonTurtle/PythonTurtle/blob/master/tox.ini#L42) this will now work?

**Comment by cclauss** [comment]
Pillow is the problem...

**Comment by bittner** [comment]
I'm really sorry you had to close this PR. I'm grateful you put in the extra mile and tried to make it work.

It's good feedback though that we now are advised to watch out for Pillow to be the problem when jumping on the 3.9 train. Luckily, there are literally thousands of Pillow users out there, so this will soon be noticed and fixed in any case, most likely. Also, we're not strictly dependent on Python 3.9 with the binaries built using PyInstaller, IIUC. That's good.

Thanks again! :medal_sports:

**Pull request closed without merging**
