### PR TITLE
Release v0.3.2

### PR DESCRIPTION
**Pull request by bittner**
This is to prepare a simple, automated release, which we will trigger by pushing a Git tag to the `master` branch once this PR is merged.

We will then be able to witness how the newly added feature of pushing the build artifacts (Windows EXE and GNU/Linux ELF binary) to the GitHub repository's [Releases](https://github.com/PythonTurtle/PythonTurtle/releases) takes place.

### CODE REVIEW

**Comment by bittner** [comment]
@cclauss, @cool-RR, I pushed a Git tag to `master`, which triggered the [new build process](https://github.com/PythonTurtle/PythonTurtle/actions?query=workflow%3ABuild*). The binaries are attached, wrapped in zip archives, but they are not published in the [Releases](https://github.com/PythonTurtle/PythonTurtle/releases) section of our repository. :worried:  We need to find out why.

More results
--------------

The downloaded GNU/Linux ELF binary does not have executable permissions after being extracted from the ZIP file. The PythonTurtle ELF binary doesn't find wxPython, even though it is installed.

```console
$ chmod +x PythonTurtle
```
```console
$ ./PythonTurtle 
wxPython doesn't seem to be installed. You need to install the appropriate prerequisites for your operating system.
Please consult the installation instructions in the README at https://github.com/PythonTurtle/PythonTurtle#installation
```
```console
$ dpkg -l python3-wxgtk4.0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                           Version              Architecture         Description
+++-==============================-====================-====================-=================================================================
ii  python3-wxgtk4.0               4.0.1+dfsg-2         amd64                Python 3 interface to the wxWidgets Cross-platform C++ GUI toolki
```

Publishing the new version [on PyPI](https://pypi.org/project/PythonTurtle/) fails with GitHub Actions, currently, Travis CI still seems to succeed though. The new can successfully be installed and run using usually Python installation methods.

```console
$ python3 -m pip install PythonTurtle
Collecting PythonTurtle
  Downloading https://files.pythonhosted.org/packages/5e/df/b83ffcf5626d59af2247d257cb252996df0559f2e07bec3de1bad9a619f0/PythonTurtle-0.3.2-py3-none-any.whl (518kB)
    100% |████████████████████████████████| 522kB 257kB/s 
Installing collected packages: PythonTurtle
Successfully installed PythonTurtle-0.3.2
```
```console
$ PythonTurtle
```

Can one of you [download and try](https://github.com/PythonTurtle/PythonTurtle/actions/runs/271486780) the Windows EXE, to find out whether is works?

**Comment by cclauss** [comment]
#152 `Install wxPython and make the ELF executable` should fix the Linux ELF.

**Comment by cool-RR** [comment]
@bittner I tried the Windows EXE now. It doesn't show any window and it exits immediately.

**Comment by cclauss** [comment]
Did you try the .exe from #152?  I do not have a Windows box.

**Comment by cool-RR** [comment]
I tried the one that Peter linked to above. Is that a different one?

**Pull request merged**
