### PR TITLE
version changed

### PR DESCRIPTION
**Pull request by Devansh2005**
Updated .pydevproject file

### CODE REVIEW

**Review by dev1920 — APPROVED** [review]

**Review by cool-RR — APPROVED** [review]

**Comment by Devansh2005** [comment]
Hi @cool-RR  can you please put the label to "hacktoberfest accepted" in my merged PR.

**Comment by cool-RR** [comment]
Ah, I was wondering what was the point of this PR, I thought it was because someone wanted to actually work on PythonTurtle using PyDev, not score points to get a t-shirt or whatever. I'm not into that, sorry.

**Comment by Devansh2005** [comment]
Its ok.. I was completely looking into Python Turtle. Sorry if my comment offends you.

**Comment by bittner** [comment]
> Hi @cool-RR can you please put the label to "hacktoberfest accepted" in my merged PR.

LOL, I suspected something like that might be the trigger. Hah! :smirk: 

[Hacktoberfest really sucks!](https://dev.to/thewdhanat/digitalocean-s-hacktoberfest-is-hurting-open-source-2g99) It attracts sluggish developers doing poor service to the community.

**Comment by Devansh2005** [comment]
Great. I'm again sorry everyone in this community. You can revert my changes. I followed the bottom up approach to learn. That is why I forked and tried to do "sluggish things". For the next time I'll try to learn first then contribute. 
Thank You for making me feel shame @bittner  "Awesome Developer".  I'm really a kid  amongst all you guys. All i want you to just pardon me for making this PR and asking for something really "sluggish".

**Comment by bittner** [comment]
Devansh, seriously, read what I write. Don't interpret and invent things that are not written there.

Hacktoberfest has created all this mess. Would you have come here without Hacktoberfest? If yes, your contribution would have been super-welcome! (Not only "welcome"—*super-welcome*!)

Ram, the original author of this software, is not the type of person who would [react astonished](https://github.com/PythonTurtle/PythonTurtle/pull/154#issuecomment-704799058) unless there would be reason for being surprised. Surprised the bad way.

Don't make other people believe you're a poor victim of malicious, hostile Open Source project maintainers. You've landed in the wrong project for that. I mean it.

## Recommendations

If you want to learn:

* Use PythonTurtle to learn Python.
* Use the PythonTurtle project to learn how to do software and automation.
* Make meaningful contributions *when you really mean to contribute*.

If you want to contribute:

1. Open an issue before attempting a PR (unless the change is obvious) to discuss your plans.
1. When you open a PR, describe your motivation for the changes in detail. Be transparent (don't make maintainers be surprised later). If you're unsure explain that, too!

Also, with all the communication, be sure to understand what is being criticized. Usually it's the code, processes, organizations, behavior. Only ill-intended people criticize people, human beings.

**Comment by Devansh2005** [comment]
A lot to learn from you sir @cool-RR , @bittner.

**Pull request merged**
