### PR TITLE
Rename workflows, prepare releasing binaries (stub)

### PR DESCRIPTION
**Pull request by bittner**
Follow-up on #156.

- Adds stub of releasing binaries to publish workflow
- Renames the workflows using verbs

### CODE REVIEW

**Comment by cool-RR** [comment]
Is this ready for review?

**Comment by bittner** [comment]
Yes, as soon as the jobs all pass ... and if the stub of releasing binaries doesn't do any harm.  :smirk:

**Comment by cool-RR** [comment]
Okay. My preference is that PRs should be draft until they are ready for review, because otherwise I get automatic notifications and then see that my attention is not really needed.

**Comment by bittner** [comment]
Feel free to merge! :rocket:

**Review by cool-RR — APPROVED** [review]

**Comment by bittner** [comment]
> My preference is that PRs should be draft until they are ready for review

That would mean that _every_ PR must be _opened_ with the draft status right from the start. That would be cumbersome and makes little sense (unless GitHub implements this as an automatic behavior).

I think we can agree on the usual understanding of how PRs work on GitHub:

1. As long as build jobs (check, tests) are running you don't need to take action as a human reviewer.
1. If jobs are failing they should be fixed first, only then a holistic human review shall be performed.
1. A PR should not be merged as long as there are build jobs running that have not completed successfully.

Everything else would be a rather custom understanding of how things work here on GitHub. Maybe you're used to something else from a different environment?

**Comment by cool-RR** [comment]
Why would it be cumbersome to open as draft? If you're using the `gh` tool
to create pull requests, the `-d` flag does it. If you're using the GUI,
it's just one extra click on the down arrow.

Anyway, I'll let this go, seeing it's important to you.

**Comment by bittner** [comment]
I think you have to accept the fact that most people won't jump to GitHub immediately the moment they receive a notification. This is maybe very specific for your situation. If you give a PR a few minutes or hours to mature the situation will usually be crystal-clear and there will be nothing to complain about.

Thanks anyway for merging this in so quickly! That's the positive side of you reacting so instantly! :joy:

**Pull request merged**
